### ISSUE TITLE
website spam

### ISSUE THREAD

**Issue by MysticalOS** [funkydude/BadBoy#105]
please add wowhunt dot com

I'm seeing more and more of these bots advertising this website which does illegal carries (piloting/account sharing) for real money transactions. Pretty much all these bots use some form of wowhunt dot com (either typing it out with actual . and no spaces) or doing it how I'm doing it here etc.

**Comment by solidus0079** [comment]
yeah and boosts4gamers dot com

Those two real money sales websites have gotten pretty bad

![wowscrnshot_011319_124948](https://user-images.githubusercontent.com/4224799/51088803-4d0cd100-1732-11e9-887d-57e4060cfd33.jpg)

**Comment by funkydude** [comment]
There is a templace on these issues for a reason. Use it or nothing will be done.

Also don't hijack other peoples reports, open your own.
