### ISSUE TITLE
Auto report issue

### ISSUE THREAD

**Issue by xwmario** [funkydude/BadBoy#106]
Hello, i got reported and got chat silenced, i spoke to a blizzard staff with respect to this. 
Can you please take a look into this :)
![image](https://user-images.githubusercontent.com/16833/52537386-40de5880-2d5e-11e9-9ee0-76e5027655b0.png)

**Comment by funkydude** [comment]
Nothing will be changed if you do not provide the message for me to verify.

**Comment by xwmario** [comment]
> 
> 
> Nothing will be changed if you do not provide the message for me to verify.

Hello this is the macro which i used. Hope it helps


<Oblivion Boost Community> Selling Battle Of Dazar'Alor Normal/Heroic, Jaina Normal/Heroic, Mythic Plus (6-10 Keys), Leveling (110-120), Mounts, PvP (2s/3s/Rbg) /w for more info or to book a spot

**Comment by funkydude** [comment]
Thanks but this message isn't reported by BadBoy. You're either mistaken or you've changed the message since the issue occurred or you were manually reported.
