### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by Addonman** [funkydude/BadBoy#110]
Count: 1
Message: ..\AddOns\BadBoy\BadBoy.lua line 284:
   bad argument #1 to 'CanReportPlayer' (Usage: local canReport = C_ReportSystem.CanReportPlayer(playerLocation))
Debug:
   [C]: ?
   [C]: ?
   BadBoy\BadBoy.lua:284:
      BadBoy\BadBoy.lua:262
Locals:

**Comment by funkydude** [comment]
Duplicate of #108
