### ISSUE TITLE
Doesn't work for Elysium WoW TBC

### ISSUE THREAD

**Issue by JaggedOne** [funkydude/BadBoy#117]
I downloaded and installed v8.2.4 for Elysium's new TBC client. It shows up as installed and ok in the Addons list at the character selection screen, but it does not appear to work. I do not see a load msg, and nothing happens when I type "/badboy" in the chat box. My AH toon in Stormwind is immediately inundated by gold seller's spam, over and over, just as before I installed BadBoy.

**Comment by funkydude** [comment]
Cool.

**Comment by JaggedOne** [comment]
You say "Cool" and then close this ? Apparently I don't understand how things work here. After making a report that this addon doesn't work on Elysium's new TBC client, I don't find "Cool" to be much help....
