### ISSUE TITLE
Badboy errors in Classic

### ISSUE THREAD

**Issue by rruggles** [funkydude/BadBoy#119]
Error found thru BugGrabber/BugSack:

7x BadBoy\Generate.lua:5: attempt to index a nil value
BadBoy\Generate.lua:5: in function `gnt'
BadBoy\BadBoy-v8.2.5.lua:5: in main chunk

Locals:
u = 279
(*temporary) = <function> defined =[C]:-1
(*temporary) = <function> defined =[C]:-1
(*temporary) = <function> defined =[C]:-1
(*temporary) = nil
(*temporary) = 279
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to index a nil value"
t = <table> {
 clickToReport = "|cffeda55fClick|r to report, |cffeda55fAlt-Click|r to dismiss."
 noAnimate = "Disable button pulse animation"
 is = <function> defined @BadBoy\Generate.lua:34
 frequentButton = "Show the button more frequently"
 spamTooltip = "Show spam in button tooltip"
 spamBlocked = "BadBoy: Spam blocked"
 gnt = <function> defined @BadBoy\Generate.lua:4
 frequentButtonTip = "To reduce player annoyance the report button will not always show.
Enable this to always show the button asking to report and show it faster."
}

**Comment by funkydude** [comment]
Don't use the live version of BadBoy on classic. Use the classic version.

**Comment by rruggles** [comment]
I would love to, where is it located?
Cheers!

**Comment by funkydude** [comment]
It's on CurseForge. I recommend you use the Twitch desktop client to manage this for you.

**Comment by rruggles** [comment]
I already use Twitch for my addon updates and also note that the following are in both the Retail and Classic .TOCs
## Interface: 80200
## Version: v8.2.5
## Title: BadBoy

So you can see my confusion. The version I was using is from WOWUI, with has a Classic section, from where I downloaded it from.
As a fellow addon author I was just trying to help out.
Cheers!

**Comment by funkydude** [comment]
I don't have any of my Classic addons on WoWUI because it doesn't support having 2 addons on 1 page. Twitch is the only viable place to get my classic compatible addons.
