### ISSUE TITLE
Lua Warning (nil value)

### ISSUE THREAD

**Issue by eusi** [funkydude/BadBoy#121]
Message: Interface\AddOns\BadBoy\Generate.lua:5: attempt to index a nil value
Time: Thu Oct 17 20:14:55 2019
Count: 1
Stack: Interface\AddOns\BadBoy\Generate.lua:5: attempt to index a nil value
[C]: ?
Interface\AddOns\BadBoy\Generate.lua:5: in function `gnt'
Interface\AddOns\BadBoy\BadBoy.lua:5: in main chunk

Classic WoW.

**Comment by funkydude** [comment]
You're trying to use the retail version of BadBoy on classic WoW when you should be using the classic specific version. You should install the Twitch client to manage this for you.

If you're already using the Twitch client, try restarting your PC and loading it up again. If it still doesn't offer you the correct version, you will need to uninstall BadBoy and reinstall it.

**Comment by eusi** [comment]
> If it still doesn't offer you the correct version, you will need to uninstall BadBoy and reinstall it.
Nice, this did the trick!
It seems Twitch downloaded the wrong version at the very first time. 
Thanks man!
