### ISSUE TITLE
Block channel invites

### ISSUE THREAD

**Issue by theAnton81** [funkydude/BadBoy#122]
The only gold spam I've seen on Classic thus far is channel invites.
Some random person invites you to join a randomly named channel. Usually the channel name resemble a domain name, but with some random number and or letters thrown in.

I don't know if you play Classic and maybe have seen this yourself, but would it be possible to block something like that, or perhaps it is already blocked by the level filter if they are below the designated level?

Obviously, if this is something that would require a massive amount of work, I totally understand that you might not want tot commit to it.

Thank you in advance for your consideration.

**Comment by fulzamoth** [comment]
This can be done on the _Social_ page of the _Interface Options_ menu. Blizz still has a message in the chat frames that says you blocked it though. Be nice to see that gone.

**Comment by Hantunaar** [comment]
^Pretty much this. Blizzard allows you to block the pop-up but it still appears in chat and there is nothing to do about it. Well the game is only 16 years old afterall, they probably didn't get time to do anything against this kind of behavior, right? Anyway I wish Badboy could hide it so the only thing that tells me I get invited to another gold seller channel would be the shield icon to block/report.

**Comment by Richu58** [comment]
Gonna try https://www.curseforge.com/wow/addons/hidechatinvitespam to see if it does it. Maybe see if what it does can be added into Badboy?

**Comment by fulzamoth** [comment]
The invites aren't chat messages. Filtering the text could be added, but it'll require registering for CHANNEL_INVITE_REQUEST events and then filtering CHAT_MSG_CHANNEL_NOTICE_USER events. That's a different type of work than the chat message filtering Badboy does.

It's probably easier to use the dedicated addon that Richu58 linked. It's tiny and is custom built to filter those events.

**Comment by funkydude** [comment]
Is this still a problem on Classic?
