### ISSUE TITLE
Error Logging into WoW Classic

### ISSUE THREAD

**Issue by bjhinkel** [funkydude/BadBoy#123]
Date: 2019-11-26 08:58:56
ID: 1
Error occured in: Global
Count: 1
Message: ..\AddOns\BadBoy\Generate.lua line 5:
   attempt to index a nil value
Debug:
   BadBoy\Generate.lua:5: gnt()
   BadBoy\BadBoy.lua:5: in main chunk
Locals:
u = 279
(*temporary) = <function> defined =[C]:-1
(*temporary) = <function> defined =[C]:-1
(*temporary) = <function> defined =[C]:-1
(*temporary) = nil
(*temporary) = 279
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to index a nil value"
t = <table> {
 clickToReport = "Click to report, Alt-Click to dismiss."
 noAnimate = "Disable button pulse animation"
 is = <function> defined @Interface\AddOns\BadBoy\Generate.lua:34
 frequentButton = "Show the button more frequently"
 spamTooltip = "Show spam in button tooltip"
 spamBlocked = "BadBoy: Spam blocked"
 gnt = <function> defined @Interface\AddOns\BadBoy\Generate.lua:4
 frequentButtonTip = "To reduce player annoyance the report button will not always show.
Enable this to always show the button asking to report and show it faster."
}

AddOns:
  Swatter, v8.2.6511 (SwimmingSeadragon)
  WowheadLooter, v11302
  Atlas, vv1.45.01.11302
  AtlasClassicWoW, vv1.45.00.11302.05
  AucAdvanced, v8.2.6471 (SwimmingSeadragon)
  AucFilterBasic, v8.2.6497 (SwimmingSeadragon)
  AucStatHistogram, v8.2.6499 (SwimmingSeadragon)
  AucStatiLevel, v8.2.6503 (SwimmingSeadragon)
  AucStatPurchased, v8.2.6500 (SwimmingSeadragon)
  AucStatSimple, v8.2.6501 (SwimmingSeadragon)
  AucStatStdDev, v8.2.6502 (SwimmingSeadragon)
  AucUtilFixAH, v8.2.6504 (SwimmingSeadragon)
  BadBoy, vv8.2.5
  Stubby, v8.2.6510 (SwimmingSeadragon)
  BlizRuntimeLib_enUS v1.13.2.11302 <none>
  (ck=261)

**Comment by bjhinkel** [comment]
Similar Error I believe

Date: 2020-10-11 11:31:48
ID: 1
Error occured in: Global
Count: 1
Message: ..\AddOns\BadBoy\Generate.lua line 5:
   attempt to index a nil value
Debug:
   BadBoy\Generate.lua:5: gnt()
   BadBoy\BadBoy.lua:5: in main chunk
Locals:
u = 279
(*temporary) = <function> defined =[C]:-1
(*temporary) = <function> defined =[C]:-1
(*temporary) = <function> defined =[C]:-1
(*temporary) = nil
(*temporary) = 279
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to index a nil value"
t = <table> {
 clickToReport = "Click to report, Alt-Click to dismiss."
 noAnimate = "Disable button pulse animation"
 is = <function> defined @Interface\AddOns\BadBoy\Generate.lua:34
 frequentButton = "Show the button more frequently"
 spamTooltip = "Show spam in button tooltip"
 spamBlocked = "BadBoy: Spam blocked"
 gnt = <function> defined @Interface\AddOns\BadBoy\Generate.lua:4
 frequentButtonTip = "To reduce player annoyance the report button will not always show.
Enable this to always show the button asking to report and show it faster."
}

AddOns:
  Swatter, v8.2.6511 (SwimmingSeadragon)
  WowheadLooter, v11304
  Altoholic, vClassic-v1.13.5-047
  Atlas, vv1.47.04
  AtlasClassicWoW, vv1.47.02.11304.00
  AtlasLootClassic, vv1.5.6
  AtlasLootClassicData, vv1.5.6
  AtlasLootClassicDungeonsAndRaids, vv1.5.6
  AucAdvanced, v8.2.6471 (SwimmingSeadragon)
  AucFilterBasic, v8.2.6497 (SwimmingSeadragon)
  AucStatHistogram, v8.2.6499 (SwimmingSeadragon)
  AucStatiLevel, v8.2.6503 (SwimmingSeadragon)
  AucStatPurchased, v8.2.6500 (SwimmingSeadragon)
  AucStatSimple, v8.2.6501 (SwimmingSeadragon)
  AucStatStdDev, v8.2.6502 (SwimmingSeadragon)
  AucUtilFixAH, v8.2.6504 (SwimmingSeadragon)
  AutoDismount, v1.0.3
  BadBoy, vv8.2.5
  DataStore, vv1.13.013
  DataStoreCharacters, vv1.13-013
  Stubby, v8.2.6510 (SwimmingSeadragon)
  BlizRuntimeLib_enUS v1.13.5.11305 <none>
  (ck=336)

**Comment by funkydude** [comment]
You're using the wrong version of BadBoy. Install the one designed for classic wow.
