### ISSUE TITLE
No spam filter in specific groups

### ISSUE THREAD

**Issue by Sekorhex** [funkydude/BadBoy#127]
Is it normal, that Badboy don't filter the groups in the specific group? I see very often some groups with the name "boost" and it doesn't hide it.

**Comment by phuze** [comment]
Yes, this is normal.

Within the LUA environment, Blizzard made the group **name**, **comment** and **voice** strings protected. As a result, it is not possible to perform any sort of string manipulation or pattern matching. This makes it impossible for Badboy, or any other addon, to filter groups from premade LFG based on the name, comment or voice inputs.
