### ISSUE TITLE
Doesn't Block Spam :/

### ISSUE THREAD

**Issue by IonstormEU** [funkydude/BadBoy#128]
Is there no option to add certain specific words to the spam?

Sylvanas, Gallywix, Nova, Oblivion etc all this boost spam is still going full tilt on my chat.

I had an option to report something for spam, but I don't want to sit reporting it 24/7.

Being able to filter spam by key phrases and even player level would be fantastic.

**Comment by phuze** [comment]
There are plugins for BadBoy that allow you to add your own keywords, and to filter by level. It's right on the main page, under [plugins](https://github.com/funkydude/BadBoy#plugins).

> Block chat by typing in keywords BadBoy_CCleaner.
> Block whispers by player level BadBoy_Levels.

**Comment by soulmaestro** [comment]
that what the badboy_ccleaner plugin is there for...
like read the readme-file (this time with your brain switched on)
