### ISSUE TITLE
Addon broken

### ISSUE THREAD

**Issue by Snoopza** [funkydude/BadBoy#13]
After updating to the latest version, the addon seems relatively broken still.  When I go into the addon itself, this is what I see "as per screenshot"
![capture](https://cloud.githubusercontent.com/assets/20572956/19734264/32ffdffe-9ba7-11e6-949c-bbb760c4a27e.PNG)

**Comment by funkydude** [comment]
This is intended as there are no options currently, i'll clean up the layout at a later date.
