### ISSUE TITLE
Plugin idea: Block sellrun/boosting advertising

### ISSUE THREAD

**Issue by cremor** [funkydude/BadBoy#130]
It would be great if there was a plugin like BadBoy_Guilded, but for sellrun/boosting advertising.

**Comment by funkydude** [comment]
Just add the words to CCleaner?

**Comment by cremor** [comment]
Yeah that's what I do now.
But if the words (or text snippets, sometimes single words might not be enough) could be bundled in a plugin it wouldn't be necessary any more that every player maintains that list for himself.

**Comment by funkydude** [comment]
Thanks for taking the time to make the suggestion. Unfortunately I don't see myself doing this. If anything, I'd rather spend more time on CCleaner and make it more powerful.
