### ISSUE TITLE
[Request] Report from History

### ISSUE THREAD

**Issue by bolerro** [funkydude/BadBoy#131]
## Describe the problem
Unable to report using History

### What steps will reproduce the problem?
NA

### Consider attaching a screenshot below to help describe your issue (Attach directly, do not link to other websites)
NA

### What version of the addon are you using? (Stating 'latest' is not useful)
9.0.1

### Do you have an error log of what happened?
NA

### Any additional information? (example: WoW language if not English)
If possible, would like to have the option to report someone that went to History. Not sure if the API would allow this, but I do have a couple of specific people who should be reported but don't see Badboy report them (or I missed that they had). Maybe add in History when spam has been reported.

**Comment by funkydude** [comment]
Thanks for taking the time to make the suggestion. Unfortunately, it's not possible.
