### ISSUE TITLE
No Ability to Add Keywords

### ISSUE THREAD

**Issue by bolerro** [funkydude/BadBoy#136]
## Describe the problem
Not able to add keywords to help remove spam

### What steps will reproduce the problem?

1.  No real steps, just no ability to add keywords like 'WTS Boost', etc

### What version of the addon are you using? (Stating 'latest' is not useful)
v1-Classic

### Do you have an error log of what happened?
NA

### Any additional information? (example: WoW language if not English)
Also, there are no other badboy addons for classic. Would be nice to have the others as well.

**Comment by funkydude** [comment]
https://www.curseforge.com/wow/addons/badboy_ccleaner should work just fine.

>Also, there are no other badboy addons for classic. Would be nice to have the others as well.

Classic is finished and will be dead once TBC comes out so that won't happen.
