### ISSUE TITLE
Missed Spam

### ISSUE THREAD

**Issue by rowaasr13** [funkydude/BadBoy#139]
Iranian/Persian RMT on EU-Kazzak:
[spam link removed]

While working on my own un-reportable spam filter I've caught something that can be reported, so here you are. I don't know Persian, so I've looked up it on translate.google.com word-by-word and added it as second paragraph in paste. First 3 lines is spam verbatim dumped directly from ChatFrame1.

**Comment by funkydude** [comment]
Nice work, thanks!
