### ISSUE TITLE
LFG not being filtered

### ISSUE THREAD

**Issue by sinjinns** [funkydude/BadBoy#141]
Using latest version of Badboy and CCleaner but nothing is being filtered out of the LFG tool.

**Comment by sinjinns** [comment]
This is in retail wow by the way. It just doesn't seem to filter the group finder at all

**Comment by funkydude** [comment]
It hasn't been possible to filter LFG for years now. Blizz broke it on purpose unfortunately.

**Comment by slk333** [comment]
this wasted me so much time trying to understand why it did not work.

Do you think mentioning it in the description would be overkill?

In classic ERA, /world and /lookingForGroup are the main places to filter Boost announcements.

I saw this on github, but some other people will never understand why it does not work

**Comment by slk333** [comment]
@funkydude
