### ISSUE TITLE
Badboy Not Working In TBC Prepatch

### ISSUE THREAD

**Issue by Dean98** [funkydude/BadBoy#144]
## Describe the problem
CCleaner does not seem to work since the prepatch today (user noted from issues log for CCleaner that it might be a Badboy issue and not CCleaner). When using the plugin with Badboy all channels are hidden except for say, yell and emote that I know of, but General, Trade etc don't show at all. Adding or removing keywords does not function.

### What steps will reproduce the problem?

1.  Hopeful TBC update
2.  
3.  

### What version of the addon are you using? (Stating 'latest' is not useful)

9.0.5 and V1Classic

### Do you have an error log of what happened?

N/A

**Comment by Gemini1661** [comment]
Installing the Classic version of BadBoy results in no apparent in-game appearance.  

I added `or WOW_PROJECT_BURNING_CRUSADE_CLASSIC` to Line 2 of BadBoy.lua but noticed it is already going to inform users that they are "trying to run the Classic version of BadBoy on a live server." if the Project ID is a match for Classic (or BC with my addition).  Loading up in-game confirms.  Seems like this logic is backward from what it should be.  Installing Classic _shouldn't_ trigger the Classic Version Warning.

With the BC project ID added, and the warning showing, it at least confirms a portion of the addon is loaded in.  /badboy does not bring up the config menu.  Adding plugins such as CCleaner results in errors: 
[BadBoy Error Log.txt](https://github.com/funkydude/BadBoy/files/6527455/BadBoy.Error.Log.txt)

**Comment by yaparadox** [comment]
update please

**Comment by Ramzzes2804** [comment]
Is there a working version of the addon for TBC right now?

**Comment by funkydude** [comment]
Update now available on the CurseForge app.
