### ISSUE TITLE
It doesn't load  at all here.

### ISSUE THREAD

**Issue by epigramx** [funkydude/BadBoy#148]
I downloaded all the latest (9.1.0) addons of badboy with wowup and only BadBoy History appears in the Interface menu.
I even disabled ALL other addons and it still does nothing (+it's definitely set to load +tried only with the core addon).

**Comment by epigramx** [comment]
Is there a way to debug this? I'm not unfamiliar with addon usage (or even basic authoring) in this game. This is very odd behavior to me.

**Comment by funkydude** [comment]
As described in the project description on the project page, the command to open the options is `/badboy`

**Comment by epigramx** [comment]
As I had said, "only BadBoy History appears in the Interface menu." which was different than the expected behavior I was seeing from the docs of the addon. 
But it's not important to me now because after the ban of some of the spammers I don't use it anymore.

**Comment by funkydude** [comment]
The "docs of the addon" (project page description?) do not mention it being in the interface options so I have no clue how you came to the conclusion that this was "expected behavior"?
Regardless, like I said, the command is `/badboy`.
