### ISSUE TITLE
Feature Request: Level filter for channel chats. 

### ISSUE THREAD

**Issue by pandabear41** [funkydude/BadBoy#156]
## Describe the enhancement
This is an enhancement request that all channel chats especially Trade, Services, LFG chats should have a character level filter. I like to see buy/sell messages or even join groups in LFG sometimes, but it is a reoccurring problem that many scammers or RMTers (I message and they reply back with a website) are creating lvl10 characters and spamming selling x mount, WTB/WTS transmog or jailer run, or even the classic selling gold rmt messages. These messages are cluttering up chat and I don't want regularly blacklist characters when they get banned and recreate all the time.

I know there is a way that lua can call who and then cache the who per some specified time period. I don't know if this even possible or what performance implications this would add. If this is not possible, just close this issue. 

### Consider attaching a screenshot below to help describe your issue (Attach directly, do not link to other websites)
Exhibit A
![image](https://user-images.githubusercontent.com/133441/199603693-4645fb71-819f-4609-aeda-d46f6aba9fde.png)

Exhibit B
![image](https://user-images.githubusercontent.com/133441/199603780-61b07afd-3bc8-4482-9921-ead0eeeb383a.png)

Exhibit C
![image](https://user-images.githubusercontent.com/133441/199604448-c6b85638-0790-4576-ba7a-48f03a228f13.png)

**Comment by funkydude** [comment]
I think this has been asked before, but regardless, it's an old (and good) idea.
Unfortunately it requires changes on Blizzard's end to properly implement in a way that's clean and acceptable for the user experience due to the insane frequency of these messages on some servers.

**Comment by pandabear41** [comment]
Alright, hope bliz adds in better methods in the future.

**Comment by funkydude** [comment]
I'm still hopeful that Blizz will add such an API in future, so you can leave it open if you want.
