### ISSUE TITLE
Whisper window still appears despite all whispers being blocked

### ISSUE THREAD

**Issue by JeeveStobs** [funkydude/BadBoy#165]
## Describe the problem
Whisper windows still appears despite all whispers being blocked by BadBoy_Levels

### What steps will reproduce the problem?

1.  Install BadBoy and BadBoy_Levels plugin
2.  Enable option to Block All Whispers
3.  Request stranger to send whisper to test functionality

### What version of the addon are you using? (Stating 'latest' is not useful)
10.2 latest production verstion

### Do you have an error log of what happened?
N/A

### Any additional information? (example: WoW language if not English)
Enabled Block All Whispers and still see a whisper window (tab) notification for a whisper. The actual whisper message is not display however.

**Comment by funkydude** [comment]
This is working as intended. When you whisper someone you automatically give them permission to whisper you.

**Comment by JeeveStobs** [comment]
No dude it's not. I'm not sending them a whisper, I'm asking for an unsolicited whisper in another channel, such as Trade, from a stranger to test your add-on. When they send the unsolicited whisper I still see a whisper window open when their name.
