### ISSUE TITLE
WTS Services not being filtered from LFG and LFR Tool

### ISSUE THREAD

**Issue by F-Lambda** [funkydude/BadBoy#168]
This junk still showing up in the search for raids and dungeons tool: 

![image](https://github.com/funkydude/BadBoy/assets/21232805/6cdc754e-40ba-4c74-b3fc-a2081dd1bd0b)

**Comment by funkydude** [comment]
LFG tool hasn't been supported since Legion when Blizzard in their infinite wisdom decided to prevent addons from scanning the text, sorry.

**Comment by F-Lambda** [comment]
Ah, okay. Would it be alright if you update the addon description then, noting that it's not available (for retail at least)? Because the description still lists it as available.
