### ISSUE TITLE
Missed Spam in the LFG finder

### ISSUE THREAD

**Issue by mohamad97-dev** [funkydude/BadBoy#169]
**DO NOT POST SPAM DIRECTLY**
Post text (not screenshots) on <https://pastebin.com/> and link it here.
LFG tool doesnt seem to filter any "WTS Mythic 10/15/17 FREE LOOT" groups at all anymore. I'm seeing all sellers when using the LFG tool.

**Comment by Sanual** [comment]
Just wanted to confirm that it doesn't filter the spam in LFG finder for me as well. Hope this can be fixed next expac when season 1 starts. This was a life saver during DF hiding the sales in LFG finder.

**Comment by funkydude** [comment]
Blizz purposely broke the ability to scan text in the LFG tool a long time ago.
