### ISSUE TITLE
Lua Errors

### ISSUE THREAD

**Issue by TheNewDarkOne** [funkydude/BadBoy#17]
32x BadBoy\BadBoy-v7.1.1-5-gf5b6ada.lua:790: Usage: BNGetGameAccountInfoByGUID(GUID)
[C]: ?
BadBoy\BadBoy-v7.1.1-5-gf5b6ada.lua:790: in function <BadBoy\BadBoy.lua:789>
BadBoy\BadBoy-v7.1.1-5-gf5b6ada.lua:800: in function <BadBoy\BadBoy.lua:795>

Locals:

**Comment by ceylina** [comment]
Can confirm even with version v7.1.1-7-g18630b0

2x BadBoy\BadBoy-v7.1.1-6-g63f3bf1.lua:746: Usage: BNGetGameAccountInfoByGUID(GUID)
[C]: ?
BadBoy\BadBoy-v7.1.1-6-g63f3bf1.lua:746: in function <BadBoy\BadBoy.lua:745>
BadBoy\BadBoy-v7.1.1-6-g63f3bf1.lua:756: in function <BadBoy\BadBoy.lua:751>

Locals:
(*temporary) = nil


Pretty sure this is a 7.1 foul up by Blizzard ;)

**Comment by funkydude** [comment]
Thanks, fixed.
