### ISSUE TITLE
Add An Option to Block User

### ISSUE THREAD

**Issue by Machou** [funkydude/BadBoy#19]
Hello,

Is it possible to add an option to block the players who write spam, but not in the blocks list Blizzard, but in that of BadBoy, so you need create this block list :)

Then, to share it via chat channels, be it automatically synchronizes with all players of the world through discussions channels, for example.

(Sorry My Bad English o/)

**Comment by funkydude** [comment]
Regarding your first suggestion, I believe there are already "ignore list" type addons in existence. If these are buggy or not maintained, I'd be happy to make one and publish it. It is not an area I've looked into, so let me know.

Regarding your second suggestion, that will never happen. It is an idea that can be abused to block legitimate users. You'd need so many safeguards and approval messages/popups that it isn't worth it.

**Comment by Machou** [comment]
Yep i understand.

Ok thanks you. i Close This Issue
