### ISSUE TITLE
missed spam

### ISSUE THREAD

**Issue by erinpac** [funkydude/BadBoy#30]
http://pastebin.com/pLCNA3W8

**Comment by funkydude** [comment]
This one is already detected, please make sure the addon is enabled. Are you sure you pasted the full text?

**Comment by erinpac** [comment]
Yes; I added a copy/paste chat mod to copy the messages directly just to be sure it got any weird characters (hence it including the toon names).  It seems to be removing many other things, and I updated it right before posting.   I haven't seen a whole lot of this particular message though - only that single one, so maybe something very particular and weird made that not match the filter...  unless the next line was a fake message from another person I'm not sure what though (and that would be odd - mods tend to mess up that sort of thing).

It being the only one I've seen of that is why it wasn't in the earlier ticket.  The two in that issue had been showing up constantly lately, and then this one lone one just happened to pop up while I had everything open.   
Oh well... if it seems to be caught, then who knows... if I see it again, perhaps.
Thanks.
The g4game one was getting really incredibly persistent and annoying.  They were spamming with several people at once (and changing people every minute or two so it was hard to spam report them) on one of my servers.

    On Wednesday, November 16, 2016 5:36 PM, funkydude <notifications@github.com> wrote:
 

 This one is already detected, please make sure the addon is enabled. Are you sure you pasted the full text?—

**Comment by funkydude** [comment]
I'd recommend BasicChatMods ;)
