### ISSUE TITLE
error popping up.

### ISSUE THREAD

**Issue by HolgerDKz** [funkydude/BadBoy#35]
1x BadBoy\BadBoy-v7.1.21.lua:752: Usage: BNGetGameAccountInfoByGUID(GUID)
[C]: ?
BadBoy\BadBoy-v7.1.21.lua:752: in function `BadBoyIsFriendly'
BadBoy_Levels\BadBoy_Levels-v7.1.1.lua:147: in function `filterFunc'
Prat-3.0-3.6.19\services\chatsections.lua:49: in function <Prat-3.0\services\chatsections.lua:42>
Prat-3.0-3.6.19\services\chatsections.lua:317: in function `SplitChatMessage'
Prat-3.0-3.6.19\addon\addon.lua:266: in function <Prat-3.0\addon\addon.lua:259>
(tail call): ?
(tail call): ?
WIM\Modules\History-History.lua:245: in function `fun'
WIM\WIM-3.7.10.lua:293: in function `CallModuleFunction'
WIM\Sources\WindowHandler.lua:1348: in function <WIM\Sources\WindowHandler.lua:1318>
(tail call): ?
WIM\Modules\WhisperEngine.lua:192: in function <WIM\Modules\WhisperEngine.lua:178>
WIM\Modules\WhisperEngine.lua:315: in function `handler'
...s\WIM\Libs\LibChatHandler-1.0\LibChatHandler-1.0-23.lua:274: in function <...s\WIM\Libs\LibChatHandler-1.0\LibChatHandler-1.0.lua:259>
...s\WIM\Libs\LibChatHandler-1.0\LibChatHandler-1.0-23.lua:326: in function <...s\WIM\Libs\LibChatHandler-1.0\LibChatHandler-1.0.lua:314>

Locals:
(*temporary) = "0x0300000000000000"

**Comment by funkydude** [comment]
Not a BadBoy issue, but I've added some debug in the latest alpha.

**Comment by funkydude** [comment]
Are you receiving any debug messages?

**Comment by HolgerDKz** [comment]
No, only error message i originally posted.

**Comment by funkydude** [comment]
You are still receiving the same error on the latest version? That should not be happening.

**Comment by HolgerDKz** [comment]
No, what i meant was, that the only error message i have seen is the one i originally posted.

I havent seen that message lately.

**Comment by funkydude** [comment]
It was from receiving a whisper and if I was to take a guess I'd say it was related to WIM.

**Comment by funkydude** [comment]
For reference: A user on WoWI also has this issue. The root was an addon called TradeForwarder, which passes data with empty args to WIM, and WIM tries to filter it using BadBoy, causing the GUID error (GUID being "").

That issue seems disconnected to the one reported here, but the results were the same. Closing for now as we have no more information.
