### ISSUE TITLE
Patreon mention ingame

### ISSUE THREAD

**Issue by Kanegasi** [funkydude/BadBoy#55]
I really love your addon and I hope you get the support you desire to continue. However, I do not want you to get blacklisted by Curse. Mentioning any form of donation, real or implied, ingame is not allowed by Blizzard and Curse will moderate your addon accordingly once they get wind of it. If you are familiar with the "donate beer" debacle with OQueue back in Mists, it's that serious.

Please remove the patreon mention ingame before you get in trouble :(

**Comment by funkydude** [comment]
It's a changelog.
