### ISSUE TITLE
Premade groups

### ISSUE THREAD

**Issue by Dusiukas** [funkydude/BadBoy#56]
issue is with  new  badboy filter $ Report spam   tool  in LFG 
then you go to  Premade Groups    and use filters  PGF    and press buton  filers  are ignered and allresults are displayed 
![image](https://cloud.githubusercontent.com/assets/25111776/21949317/1f9726b8-d9e9-11e6-9499-b84e90c7924d.png)

after pressing button

![image](https://cloud.githubusercontent.com/assets/25111776/21949326/2d1c340e-d9e9-11e6-93f2-ccdc134a4267.png)

**Comment by Dusiukas** [comment]
Please  allow us  to disable  it for looking for group  window

**Comment by funkydude** [comment]
I'll look into adding compatibility for this addon.

**Comment by gnuheike** [comment]
Confirmed the same behaviour with https://mods.curse.com/addons/wow/premade-filter

**Comment by Koveras** [comment]
+1 for "Please allow us to disable it for looking for group window"

**Comment by funkydude** [comment]
I have contacted the authors of both of those addons to see how they would prefer integration to take place.

> +1 for "Please allow us to disable it for looking for group window"

No, bring valid arguments and debates, not plus 1's.

**Comment by Dusiukas** [comment]
until when  they will agree or  disagree to integrate it   can you make option to disable it ?

**Comment by funkydude** [comment]
I will add some code for now to disable it if either of those addons is detected.

**Comment by halchak** [comment]
In LFG can the button be moved to the lower left, just under "Premade groups" or a checkbox in options to disable for LFG. I would prefer it just be moved though. btw, thanks for great addon!

**Comment by funkydude** [comment]
@Dusiukas Do you use alpha versions? Can you test if the latest alpha now respects your filters when you click the button?

**Comment by Dusiukas** [comment]
I will be able to test it tommorow morning only.

**Comment by gnuheike** [comment]
@funkydude nope. it doesn't
http://imageshack.com/a/img922/6428/L1Bcq8.jpg
http://imageshack.com/a/img923/3999/kw6HLu.jpg

**Comment by funkydude** [comment]
@gnuheike The author of PGF told me they do work fine now. Are you sure you were using the alpha release?

**Comment by halchak** [comment]
@funkydude 

	local f = CreateFrame("Button", nil, PVEFrame, "UIPanelButtonTemplate")
	f:SetPoint("BOTTOMLEFT")

http://imageshack.com/a/img923/8062/YeXSQN.jpg

**Comment by funkydude** [comment]
The fix for PGF is now in the latest release.

Waiting for a reply from the PremadeFilter author.

**Comment by fratzi** [comment]
I would like to disable the LFG filtering at all!

**Comment by funkydude** [comment]
> I would like to disable the LFG filtering at all!

Installs anti-spam addon.
"I want to disable this anti-spam functionality"
...no.

Closing this. No reply from PremadeFilter author and original issue is resolved. Open new tickets for any other addons that don't work.
