### ISSUE TITLE
Spam button in premade group finder [bug]

### ISSUE THREAD

**Issue by WimVDK** [funkydude/BadBoy#57]
I noticed BB can nos filter spam. But for the love of god, make it a ONE CLICK setting. Every time you do a refresh, there's that damn "Filter & report spam" button again in the middle of the grp finder and right over any entry. It's annoying enough to make me consider disabling the addon.

**Comment by funkydude** [comment]
Apparently the button isn't required at all, I'll remove it and have it auto filter.
