### ISSUE TITLE
Option to disable "spam icon" at chat

### ISSUE THREAD

**Issue by fratzi** [funkydude/BadBoy#58]
Hi,

i'm missing an option to disable the "spam icon" near the chat. I just want a silent background filter. Also I can't hover over items in chat, because the shield is active and forces me to report the spam.

Best regards
fratzi

**Comment by funkydude** [comment]
No, suggest better methods, not requests to disable it.

**Comment by fratzi** [comment]
Sorry, maybe I wasn't clear enough. My suggestion was to let the user decide if he wants to report spam or not by giving him a checkbox in the options menu.

Like:
[  ] Disable Reporting Icon

I personally never report any spam or guild recruitement, I just don't want to see it.

**Comment by funkydude** [comment]
I'm aware of what you meant. The option to disable reporting will not be added.
However, anyone is welcome to suggest improvements to it.
BadBoy_CCleaner clearly states it does **not** report spam.

**Comment by WimVDK** [comment]
I've been out of game for a while until i started playing again about 2 months ago. Is there any way BB can auto report like it used to? Or has the API changed that's no longer possible?

**Comment by funkydude** [comment]
Unfortunately not. Some "smart" person at Blizzard thought it would be a good idea to require a hardware event (mouse click, keyboard press) to report people. All it has done is annoyed people and reduce the amount of reports for spammers.

**Comment by WimVDK** [comment]
In that case, i would also like the option to disable reporting and simply go into "blocking mode". Blizzard doesn't seem to do anything about the spammers anyway. Same ppl online for weeks, 24/7 spamming the same shit over & over

**Comment by funkydude** [comment]
I've seen Blizz ban spambots as soon as 15 minutes. Using the same name is a nifty demotivational trick.

**Comment by WimVDK** [comment]
Well not on doomhammer i guess. Therefore i would really like that option, but ultimately the final decision is yours.

**Comment by funkydude** [comment]
The time it takes to ban spambots is directly affected by how many reports are received for that user, hence why spambots use the same name, so people don't report them.
