### ISSUE TITLE
Lua error caused by BadBoy

### ISSUE THREAD

**Issue by b-morgan** [funkydude/BadBoy#63]
I am getting the following Lua error which I believe is a result of the BadBoy call on line 473 of BadBoy.lua:

`LFGListSearchPanel_UpdateResults(LFGListFrame.SearchPanel) -- Finally, feed frame holding the results to the panel`

5x FrameXML\LFGList.lua:2094: attempt to perform arithmetic on local 'appDuration' (a nil value)
FrameXML\LFGList.lua:2094: in function `LFGListSearchEntry_Update'
FrameXML\LFGList.lua:2164: in function <FrameXML\LFGList.lua:2160>

Locals:
self = LFGListSearchPanelScrollFrameButton7 {
 0 = <userdata>
 Selected = <unnamed> {
 }
 Highlight = <unnamed> {
 }
 isApplication = true
 DataDisplay = <unnamed> {
 }
 ActivityName = <unnamed> {
 }
 VoiceChat = <unnamed> {
 }
 ExpirationTime = <unnamed> {
 }
 resultID = 278
 CancelButton = <unnamed> {
 }
 Name = <unnamed> {
 }
 Spinner = <unnamed> {
 }
 expiration = 438700.545
 ResultBG = <unnamed> {
 }
 ApplicationBG = <unnamed> {
 }
 PendingLabel = <unnamed> {
 }
}
resultID = 278
_ = nil
appStatus = nil
pendingStatus = nil
appDuration = nil
isApplication = true
isAppFinished = nil
(*temporary) = 438704.021
(*temporary) = 438704.021
(*temporary) = "RIGHT"
(*temporary) = <unnamed> {
 0 = <userdata>
}
(*temporary) = "LEFT"
(*temporary) = -3
(*temporary) = 0
(*temporary) = <userdata>
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to perform arithmetic on local 'appDuration' (a nil value)"

**Comment by funkydude** [comment]
This is a Blizz error, not a BadBoy error. It is caused by the failure of appDuration to have a value. It is a known issue to Blizzard.

Also if you're using an old version of BadBoy, update. The old version had a chance to trigger this on log in.
