### ISSUE TITLE
Premade Group Filters

### ISSUE THREAD

**Issue by vengent** [funkydude/BadBoy#65]
It seems to be blocking far more than just regular spam, but also typical "carry" groups (your key, our carry).

Is it possible to finetune this? Right now I have to disable the addon to find these groups.

**Comment by funkydude** [comment]
You do not get the same groups every time unless there is a lack of groups.

I verify this daily, and there are no problems.

**Comment by vengent** [comment]
I'm aware of not getting the same groups.  I refreshed it about 3 dozen times and never saw a single carry group.  I disabled your addon and saw one immediately.  I've done this on 3 separate occasions now on different characters.

**Comment by funkydude** [comment]
Show me a screenshot of you mousing over said group please.

**Comment by funkydude** [comment]
Can you not reproduce the problem?

**Comment by vengent** [comment]
Not consistently.  Maybe its just confirmation bias, still "seem" to see more when disabled, but am able to see some while enabled.  Thanks for reviewing.
