### ISSUE TITLE
Missed Spam

### ISSUE THREAD

**Issue by Barleduq** [funkydude/BadBoy#67]
I'm sorry, I don't know how to post to pastebin and I don't know how to refer to the weird characters like hearts and stuff.  I took a shot of my general chat box with the /say spam in it, and uploaded it to imgur: <snip>

Hopefully that's acceptable. Thanks for all the work done here.

**Comment by funkydude** [comment]
No, screenshots are not acceptable, as stated in the default layout of the ticket.

1. Use a chat addon like BasicChatMods.
2. Click the timestamp to copy the chat.
3. Go to pastebin.com and paste the chat into the large box.
4. Set paste expiration to something sensible, like 1 week, click create new paste.
5. Copy and paste the web address from your browser, here.

All this being said, from looking at your screenshot, the spam is already blocked, leading me to conclude that you may have the addon disabled.

**Comment by Barleduq** [comment]
I did check to see if the addon was enabled. It was in local, /say,
does that make a difference?
I don't use any chat addons.
Thank you for the instructions, and also for checking it anyway. I
will check, again, if that alt had the addon enabled.

No, I don't expect a response. Thank you for being busy making this
addon. It's one of the first I ever installed, and I'm positive it's
made my gaming life more pleasant by magnitudes.

-Barleduq

**Comment by funkydude** [comment]
Say is a scanned channel so that's not the problem.
If it is missed spam you'll need to use a chat mod and follow the instructions so I can verify it. But by looking at the text it should be blocked.
