### ISSUE TITLE
Missed spam

### ISSUE THREAD

**Issue by PekaFat** [funkydude/BadBoy#68]
[spam removed]

Also, where I can report missed  guild spam for BadBoy_Guilded? Because you didn't answer on issue like for month so I deleted it because I think you're just not view 'Issues' on BadBoy_Guilded repo.

**Comment by funkydude** [comment]
Most of what you reported is not spam. If you don't like boosting, filter it using CCleaner. Selling boosts for gold is not against the ToS. The 2 or 3 legit spammers will be blocked next update.

Guild spam is low priority, you can report on the Guilded ticket tracker and I'll get round to it when I have time. The addon filters ~90% of guild spam, I am happy with this number.

**Comment by PekaFat** [comment]
There is another new spam:
https://pastebin.com/PgSXPg9F

**Comment by funkydude** [comment]
They are both already blocked in the new update.
