### ISSUE TITLE
Missed Spam

### ISSUE THREAD

**Issue by p-90** [funkydude/BadBoy#69]
There is a new type of scam/boost selling for real money and account theft in the Spanish realms.

[fixed]

**Comment by funkydude** [comment]
What realm?

**Comment by periflo90** [comment]
I've seen it in Minahonda and Exodar (they're connected).

**Comment by thepaladinnz** [comment]
Missed spam 18/05/17, Barthilas(US)
https://pastebin.com/mAMYWywW

**Comment by funkydude** [comment]
@thepaladinnz other peoples tickets are not where you report missed spam, open your own.
