### ISSUE TITLE
Any way to implement TradeForwarder?

### ISSUE THREAD

**Issue by Alaeya** [funkydude/BadBoy#71]
First, love this addon.
I did search on google but didn't find a solution.
Is there any way to monitor and filter the TradeForwarderchat?
https://mods.curse.com/addons/wow/tradeforwarder
TradeForwarder, as the name suggests, is an addon, which will copy the tradechat and post it into a privat chat channel. So you are able to read the Tradechannel even when outside of cities.

Information regarding the priv. channel:
Dump: value=GetChannelName("4")
[1]=4,
[2]="TCForwarder6IIll",
[3]=0

ChatLog:
[spam removed]

How it looks ingame:
[spam removed]

**Comment by funkydude** [comment]
Not interested in supporting what is essentially a giant hack, sorry.
