### ISSUE TITLE
BadBoy tried to call protected function Search()

### ISSUE THREAD

**Issue by Eliar** [funkydude/BadBoy#72]
1x [ADDON_ACTION_BLOCKED] AddOn 'BadBoy' tried to call the protected function 'Search()'.
!BugGrabber\BugGrabber.lua:573: in function <!BugGrabber\BugGrabber.lua:573>
[C]:: in function 'Search'
BadBoy\BadBoy-v7.2.61.lua:518: in function <BadBoy\BadBoy.lua:511>

**Comment by funkydude** [comment]
Update.
