### ISSUE TITLE
Bugsack error

### ISSUE THREAD

**Issue by Mrhgb** [funkydude/BadBoy#73]
I started getting this error today:

3x [ADDON_ACTION_BLOCKED] AddOn 'BadBoy' tried to call the protected function 'Search()'.
!BugGrabber\BugGrabber.lua:573: in function <!BugGrabber\BugGrabber.lua:573>
[C]: in function `Search'
BadBoy\BadBoy-v7.2.60.lua:518: in function <BadBoy\BadBoy.lua:511>

Locals:
nil

**Comment by funkydude** [comment]
Update.
