### ISSUE TITLE
Version v7.2.78 not being updated by Twitter app

### ISSUE THREAD

**Issue by rruggles** [funkydude/BadBoy#76]
as said by the subject, the Twitter app is failing to update Batboy. You click the update button, it does the download, etc., but the the button goes back to "Update". In checking Batboy, it is still the 7.2.77 version. When this has happened to my own authored addon, QuestGuru, it has been because I had done something that Twitter/Curse app didn't like. Might check there.

Cheers!

**Comment by funkydude** [comment]
I don't know what on earth Twitter has to do with WoW addons. Maybe you meant the Twitch app, in which case, that has nothing to do with me and is out of my control.
