### ISSUE TITLE
How do I remove the shield icon overlay from my chat permanently ?

### ISSUE THREAD

**Issue by Jaladhjin** [funkydude/BadBoy#78]
I love the "Blocker" feature.. but could totally do without the Reporter feature..

I don't want that Shield overlay..

How can I disable it permanently ?

**Comment by funkydude** [comment]
You can't and that won't change.

**Comment by Jaladhjin** [comment]
Is that some bigger picture matter of principle we can only hope to truly stop the spam by reporting it ?

**Comment by funkydude** [comment]
Yes it's a matter of principle but not it won't truly stop spam. Unfortunately nothing will truly stop spam, BadBoy curves it from becoming as severe as it once was.

**Comment by Jaladhjin** [comment]
Fair enough.. the main reason I wanted it gone was sometimes I notice when I attempt to interact with my chat window.. I have to click past the overlay obviously.. & all the chat that was there disappears.. all of it.. even "normal" stuff from trade..

I had Badboy_History installed as well to see if it was sort of.. considering it all spam since I didn't interact with the overlay quick enough..

Any idea what's happening to me ?

**Comment by funkydude** [comment]
Blizz was supposed to have fixed that bug. I'll have to speak with them again.

What server was this on, is it connected to another server, and on what server was the person you reported that caused the chat wipe (check badboy history)?
