### ISSUE TITLE
The Report Spam Overlay Shield Is Eating Non-Spam

### ISSUE THREAD

**Issue by Jaladhjin** [funkydude/BadBoy#80]
So I'm not sure how to capture something useful for you.. it doesn't happen every time I have to click past the overlay to access my chat :-/

Even if I could reproduce it on demand.. the only useful thing I could think of doing would be a video recording of it eating normal chat.. stuff in Trade & General..

I've got the History mod installed too.. is there some sort of restore type feature or will that actually prove all the non spam is getting removed ?

I've never actually used History.. just installed it for good measure..

**Comment by funkydude** [comment]
I had already inquired about this in the other ticket which you never answered.

**Comment by 123buns** [comment]
I'm having the same issues with partychat, and also guildchat. Partychat will often trigger "loot received" as spam, and simply wipe the entire chat when someone loots something. Guildchat seems random as well, but I've had issues where it's been wiped when people have linked their keystones. It's happening to people from all servers (I'm Ravencrest EU based).

**Comment by funkydude** [comment]
> Partychat will often trigger "loot received" as spam

BadBoy doesn't scan party chat or loot messages, this is not "the trigger" at all.

> simply wipe the entire chat when someone loots something

It has nothing to do with looting, the chat wipe happens after a report is submitted for a legitimate spammer. Whats happening is the game gets confused, tries to wipe chat from the spammer you reported, and wipes a massive amount of your history.

The bug itself is harmless, although annoying.

> I'm Ravencrest EU based

Do you know what realm(s) this is connected to, if any?

**Comment by 123buns** [comment]
I have general chat disabled, so I have no idea how it would detect spam from anyone inside a dungeon when only party chat is active then. No idea about connected realms. The guildchat being wiped could be due to tradechat of course, but when only partychat is active I have no idea what spammer your addon would be trying to report :thinking:

**Comment by funkydude** [comment]
It's not really disabled, it's just hidden. Spammers will still be caught.

I recommend you install _History, that way when the chat wipe happens, you can open the History panel and see exactly who was the last spammer and what server they were on (if connected).

**Comment by SpoinkyNL** [comment]
I'm having the same issue, I use ElvUI.

It sometimes occurs when I click an item/achievement link in guild chat, it'll wipe the entire session's chat history.

**Comment by bessiq** [comment]
I have this issue as well. I have the full suite of BB addons installed (and Prat 3.0, fwiw). I will try to make a note of all details when this happens, including the spammer name in BB History, and submit them to this ticket.

On a side note, it might be nice to be able to copy/paste the text from BB History. Thanks for keeping up with this addon.

**Comment by funkydude** [comment]
> It sometimes occurs when I click an item/achievement link in guild chat

It's more likely you had spam waiting to be reported, which got reported when you were going to click the link.

> On a side note, it might be nice to be able to copy/paste the text from BB History

What you can do is straight after this happens, type /reload
Then open your `BadBoy_History.lua` saved variables file located at:
`\World of Warcraft\WTF\Account\ACCOUNTNAME\SavedVariables`

It should be the last entry under the `BBHISTORY` section.

Don't post the spam, just the name-server and the server you're on.

**Comment by bessiq** [comment]
After messing around a bit, I feel like this is a problem with the Prat addon, at least in my case. It would be interesting to see if others with this issue also use Prat.

My tests were in no way extensive, but here is what I found:

- Prat enabled, BB enabled: when clicking the chat window to report, all chat text _between_ the spammer's messages is cleared (chat messages preceding the spammer's first message remains)
- Prat enabled, BB disabled: when right-clicking on a spammer's name to report them (via the default Blizzard interface), the same behavior as above occurs
- Prat disabled, BB enabled: clicking chat frame to report clears _only_ the spammer's messages
- Prat disabled, BB disabled: right-clicking spammer's name to report clears _only_ the spammer's messages

I can poke around in Prat's options to see why it might do that, or just live with the behavior, or disable Prat. I only really use it for a couple minor things anyway.

For what it's worth, the last spammer was "Ophnerianda" on the Dalaran server, which is the server I am on also. Going through the history, it appears that all spammers were on my server.

**Comment by bessiq** [comment]
Well, with Prat disabled I just reported a spammer using BadBoy, and it cleared the text between their spam messages, so idk what's going on lol. Name was Mariustero, on my server (Dalaran).

**Comment by Jaladhjin** [comment]
yeah.. I didn't look at that other ticket again.. ha.. should have mah bads :-D

I'll watch the history next time it occurs.. it isn't consistent at all :-/

sometimes it nukes.. sometimes not.. on Illidan US

**Comment by Morgana5** [comment]
Hello, /join World has become a very used, Classic wide, chat channel.  It is not a public channel but privately owned and used by the public.
Many guild/group/event/information reports are announced on this channel as well as many words and spam items that would otherwise be trapped by your wonderful mod.
Could you arrange some way to filter chat on this particular "World" chat channel please.
