### ISSUE TITLE
LUA error (BadBoy and Premade Groups Filter)

### ISSUE THREAD

**Issue by Nillx** [funkydude/BadBoy#83]
There is some kind of interaction between BadBoy and Premade Group Finder

_3x PremadeGroupsFilter\Main.lua:50: attempt to index local 'model' (a nil value)
PremadeGroupsFilter\Main.lua:50: in function `GetExpressionFromDifficultyModel'
PremadeGroupsFilter\Main.lua:87: in function `GetExpressionFromModel'
PremadeGroupsFilter\Main.lua:123: in function <PremadeGroupsFilter\Main.lua:118>
[C]: in function `LFGListUtil_SortSearchResults'
BadBoy\BadBoy-v7.3.71.lua:429: in function <BadBoy\BadBoy.lua:391>

Locals:
InCombatSkipped_

**Comment by funkydude** [comment]
Nothing here points to this being a BadBoy issue.
