### ISSUE TITLE
The filter is not working for me in Group Finder at all...

### ISSUE THREAD

**Issue by menoobslayer** [funkydude/BadBoy#86]
Does not seem to matter if I do or don't have any other group finder related add ons. It will not filter out search results, or at the least its only doing a partial filter. When I press refresh/search I get the message in the bottom left that it "filtered" out search results, but the thing is still PACKED full of spam, even stuff that I could see before I pressed search and i set keywords for is still there after I press it. Even if i press it 100 times it just keeps giving me the popup that it "removed" spam but there it is not actually removing the spam.

**Comment by funkydude** [comment]
Try with BadBoy as the only addon loaded. If this still happens, then you'll need to mouse over it to see the description, take a screenshot, and drag it into this ticket to attach it.

**Comment by funkydude** [comment]
No response, closing.
