### ISSUE TITLE
Request to have addon monitor /LookingForGroup

### ISSUE THREAD

**Issue by xyzforgottenme** [funkydude/BadBoy#87]
**DO NOT POST SPAM HERE**
Post text (not screenshots) on pastebin.com and link it here.
Use the title "missed spam".

I was wondering if we could have a setting to enable the addon to monitor the channel /LookingForGroup on the larger realms. Mostly because all the Guild spammers are moving there and it is an annoyance.

**Comment by funkydude** [comment]
BadBoy does not block or report guild spam.

If you're talking about the _Guilded plugin, a whole different addon, it already scans this channel.

**Comment by xyzforgottenme** [comment]
No I am talking about the /lookingforgroup channel. I am NOT talking about
/guild.
