### ISSUE TITLE
Quick Question.

### ISSUE THREAD

**Issue by xyzforgottenme** [funkydude/BadBoy#88]
**DO NOT POST SPAM HERE**
Post text (not screenshots) on pastebin.com and link it here.
Use the title "missed spam".

I didn't see it on curse but do the additional add-ons, such as the Guild one, monitor the chat channel /LookingForGroup? I am not talking about the channel /Guild. If so they are failing to detect Guild spam. Currently the information displayed says it only monitors Trade, General, Yell, Whispers. Yet is doesn't state anything regarding /LookingForGroup.

**Comment by funkydude** [comment]
Again, BadBoy has nothing to do with guild spam. It never has reported or blocked guild spam and never will. If you want to report issues with BadBoy_Guilded, it has it's own project page. Stop opening issues where they do not belong.

In regards to your question, if you read the BadBoy_Guilded description page:
```Removes guild advertising from public channels```
