### ISSUE TITLE
random whispers

### ISSUE THREAD

**Issue by Ninukai** [funkydude/BadBoy#94]
as soon as I log into WoW, the addon will just randomly message somebody without them even messaging me, it has happened a few times with people who messaged me either a day or to before, but now it is starting to whisper random people in my guild

**Comment by funkydude** [comment]
BadBoy doesn't whisper people, where is your evidence of this? Show screenshots.

**Comment by Sixthly** [comment]
Are you using any plugins such as BadBoy_Levels in conjunction with a chat history AddOn? Even though this shouldn't trigger any events, it might be worth checking.

**Comment by funkydude** [comment]
No response, closing.
