### ISSUE TITLE
Badboy and Listener conflict.

### ISSUE THREAD

**Issue by Zuuda** [funkydude/BadBoy#96]
The first whisper of the session will always trigger an error. It never happens again until the next session. i have tried deleting Bad Boy and BadBoy_levels as well as Listener including the variable settings, deleting cache, then reinstalling. 

Date: 2018-08-01 17:12:30
ID: 12
Error occured in: Global
Count: 1
Message: ..\AddOns\BadBoy_Levels\BadBoy_Levels.lua line 203:
   attempt to index local 'f' (a nil value)
Debug:
   (tail call): ?
   BadBoy_Levels\BadBoy_Levels.lua:203: filterFunc()
   Listener\src\listener.lua:558: ?()
   ...rer\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:145:
      ...rer\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:145
   [string "safecall Dispatcher[18]"]:4:
      [string "safecall Dispatcher[18]"]:4
   [C]: ?
   [string "safecall Dispatcher[18]"]:13: ?()
   ...rer\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:90: Fire()
   ...\AddOns\!Vendorer\libs\AceEvent-3.0\AceEvent-3.0.lua:120:
      ...\AddOns\!Vendorer\libs\AceEvent-3.0\AceEvent-3.0.lua:119
Locals:
None
AddOns:
  GarbageProtector, v
  Swatter, v7.3a.5701 (TasmanianThylacine)
  Vendorer, v3.0.0
  ACP, vr259 
  AdvancedInterfaceOptions, v1.2.4
  AngryKeystones, v
  ArtifactPowerUser, v3.2
  AskMrRobot, v62
  AtlasLoot, vv8.07.13
  AtlasLootBurningCrusade, vv8.07.13
  AtlasLootCataclysm, vv8.07.13
  AtlasLootClassic, vv8.07.13
  AtlasLootLegion, vv8.07.13
  AtlasLootMistsofPandaria, vv8.07.13
  AtlasLootWarlordsofDraenor, vv8.07.13
  AtlasLootWrathoftheLichKing, vv8.07.13
  Auctionator, v5.0.4
  AutoAcceptEnchantReplace, v
  AutoClickthrough, v
  AutoLootPlus, v1.2.3
  BadBoy, vv8.0.7
  BadBoyLevels, vv8.0.0
  BagBrother, v
  Bagnon, v8.0.0
  BagnonConfig, v8.0.0
  Bartender4, v4.8.1
  BartrubySummonPet, v1.28
  BiggerFishToFryTracker, v1.5.1
  BlizzMove, vv1.8
  BonusRollPreview, v80000.46-Release
  BrokerMemory, v1.1
  BuyEmAll, v3.5.0
  Carbonite, v8.0.0
  CarboniteQuests, v8.0.0
  ConfirmSP, v02.12
  DBMCore, v8.0.1
  DBMDefaultSkin, v
  DBMStatusBarTimers, v
  DBMVPARNOLD, v7.3.3
  DBMVPVEM, v8.0.0
  DefsCameraZoom, v80000.1
  DejaCharacterStats, v800r103
  Details, v
  DetailsDeathGraphs, v
  DetailsDmgRank, v
  DetailsDpsTuning, v
  DetailsEncounterDetails, v
  DetailsRaidCheck, v
  DetailsRaidInfoEmeraldNightmare, v
  DetailsRaidInfoNighthold, v
  DetailsRaidInfoTombOfSargeras, v
  DetailsRaidInfoTrialOfValor, v
  DetailsStreamer, v
  DetailsTimeAttack, v
  DetailsTinyThreat, v
  DetailsVanguard, v
  DressUp, v3.0.1
  EasyObliterate, v31
  EasyDisenchant, v
  Een, v1.5.3
  EmoteSplitter, v1.5.5
  ExtraQuestButton, v80000.10-Release
  FlashTaskBar, v
  FriendGroups, v8.0
  GlobalIgnoreList, v8.0.2
  GTFO, v4.46.1
  HandyNotes, vv1.5.2
  HandyNotesDraenorTreasures, v1.21
  HandyNotesLegionInstanceWorldQuests, vv1.13
  HandyNotesLegionRaresTreasures, v1.1
  HandyNotesLorewalkers, v1
  HandyNotesLostAndFound, v1
  HandyNotesPandariaTreasures, v1.06
  HandyNotesTimelessIsleRareElites, v2.32
  HandyNotesTimelessTreasures, v1.0.7
  HandyNotesTreasureHunter, v1
  HandyNotesWitheredChests, v1.2
  HandyNotesWorldMapButton, v2.6
  HideTalentAlert, vv1.4
  IgnoreEnemyEmotes, v
  ImprovedStableFrame, v3.3.1
  IncentiveProgram, vr16
  InstanceViewer, v2.0
  InstantEagle, v1.01
  ItemLinkLevel, v1.7.1
  LazyGroupFinder, v1.5
  LDBArtifact, vv1.7.2
  LegionMapZoomer, v2.0
  LegionWardrobe, v29
  Listener, v2.1.3
  MacroToolkit, vv7.3.0.2
  MacroToolkitIcons, v7.2.0.0
  Misspelled, v1.6.3
  ModelPique, v8.0.1.0 Release
  MogIt, v3.8.8
  MogItArtifact, v3.8.8
  MogItMail, v3.8.8
  MogItOneHanded, v3.8.8
  MogItOther, v3.8.8
  MogItRanged, v3.8.8
  MogItSetTransmog, v1.5.2
  MogItTwoHanded, v3.8.8
  MountJournalEnhanced, v1.8.1
  MoveAnything, v17.0.0
  NpcHider, v1.3
  Oilvl, v8.0.0
  OmniCC, v8.0.1
  OmniCCConfig, v
  ParagonReputation, v1.19
  Paste, v1.4.10
  Pawn, v2.2.22
  PersonalLootHelper, v2.08
  PetJournalEnhanced, v2.9.30
  Postal, vv3.6.0
  PounceCam, v2.4.01
  Prat30, vr1171      
  Prat30Libraries, v
  PremadeGroupsFilter, v1.17
  QuestPlates, v8.0.0.1
  RCLootCouncil, v2.8.2
  SavedInstances, v8.0.3
  ShadowedUnitFrames, vv4.2.1
  SimPermut, v1.15.0
  SimpleObjectiveProgress, vr26
  Simulationcraft, v1.10.4
  StatBlockMemory, v
  TalkLess, v1.0.4
  TidyPlates, v6.18.11
  TidyPlatesGraphite, v
  TidyPlatesGrey, v
  TidyPlatesNeon, v
  TidyPlatesQuatre, v
  TidyPlatesHub, v
  TidyPlatesWidgets, v
  Titan, v5.14.1.80000
  TitanBag, v5.14.1.80000
  TitanClock, v5.14.1.80000
  TitanGold, v5.14.1.80000
  TitanLocation, v5.14.1.80000
  TitanLootType, v5.14.1.80000
  TitanPerformance, v5.14.1.80000
  TitanPoints, v8.0.1
  TitanRepair, v5.14.1.80000
  TitanReputation, v3.9.3
  TitanVolume, v5.14.1.80000
  TitanXP, v5.14.1.80000
  TomTom, vv80001-1.0.1
  Tongues, v1.8.0
  totalRP3, v1.4.3
  totalRP3Data, v
  TradeSkillMaster, vv4.0.4
  TradeSkillMasterAppHelper, vv3.0.4
  UnsheathMove, v1.7.1.0
  WardrobeSort, vv1.4.1
  WeakAuras, v2.6.6
  WorldFlightMap, v8.0.0.2
  WorldMapZoom, v
  WorldQuestTracker, v
  XLoot, v8.0-3
  XLootGroup, v8.0-3
  BlizRuntimeLib_enUS v8.0.1.80000 <none>
  (ck=fca)

**Comment by funkydude** [comment]
This isn't a BadBoy issue.
